### ISSUE TITLE
negative numbers

### ISSUE THREAD

**Issue by iembry-USGS** [bgreenwell/ramify#13]
Hi, there seems to be an issue with negative numbers resulting in a character matrix rather than a numeric matrix.

When I view A1, it is a character matrix:

A1 <- mat("0, 0, 0, 0, 0, 6; -1, 0, 0, 0, 0, 1; 0, -1, 0, 0, 0, 0; 0, -8, 4, 0, 0, 0; -1, 0, 0, 1, 0, 0; 0, 1, -1, 0, 1, 0")

A1

When I view A2, it is a numeric matrix:
A2 <- mat(c(0, 0, 0, 0, 0, 6, -1, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, -8, 4, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 1, -1, 0, 1, 0), nrow = 6, byrow = TRUE)

A2

Can you make the changes to allow negative numbers?

Thank you.

**Comment by bgreenwell** [comment]
Fixed on the GitHub version. I'll send a new version to CRAN sometime this week as well. Thanks for reporting!
